export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FINISH = 'AUTH_FINISH';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_UPDATE_DISPLAY_NAME = 'AUTH_UPDATE_DISPLAY_NAME';
export const AUTH_UDATE_AVATAR_URL = 'AUTH_UDATE_AVATAR_URL';
export const AUTH_DELETE_AVATAR_URL = 'AUTH_DELETE_AVATAR_URL';
export const AUTH_UPDATE_EMAIL = 'AUTH_UPDATE_EMAIL';
export const AUTH_UPDATE_PASSWORD = 'AUTH_UPDATE_PASSWORD';

export const ADMIN_START = 'ADMIN_START';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_FINISH = 'ADMIN_FINISH';
export const ADMIN_FAIL = 'ADMIN_FAIL';
export const ADMIN_RESET = 'ADMIN_RESET';